module_name: Nochex Payment Gateway
compatible_versions: 2.0, 2.1, 2.2
author: Thirty Bees
category: payment
tags:
  - checkout
  - order
  - payment
  - nochex
  - apc
  - callback
description_short: The Nochex Payment Gateway module allows you to accept payments by Nochex.
description: description.md
images:
  - image-1.png
license: AFL
